services:
  - type: web
    name: springboot-thymeleaf-app
    runtime: docker
    
    plan: free
    buildCommand: ""
    startCommand: "java -jar CollegeERPSystem-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: 8080
